name: CI

on:
  push:
    paths-ignore:
      - "**/*.tgz"
      - "**/*.gz"
      - "**/release*/**"
      - "**/dist/**"
      - "**garbage-collector**"
      - "**codeql**"
      - "**/.github/workflows/tester.yml"
  pull_request:
    types:
      - closed
    paths-ignore:
      - "**/release*/**"
      - "**/dist/**"
      - "**/*.tgz"
      - "**/*.gz"
      - "**/test*/**"
  workflow_dispatch:

jobs:
    unit:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: ['18', '20', '22']

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}

            - run: yarn install

            - run: npm run lint

            - run: npm test
